# Generated by Django 5.1 on 2024-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='F.I.O')),
                ('position', models.CharField(max_length=50, verbose_name='Lavozim')),
                ('status', models.CharField(max_length=100, verbose_name='Turi')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ism va lavozim')),
                ('description', models.TextField(verbose_name="Ma'lumot")),
                ('photo', models.ImageField(upload_to='managements/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name_plural': 'Rahbariyat',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name="Ma'lumot")),
                ('photo', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
