# Generated by Django 5.1 on 2024-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_alter_employee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '4.Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name_plural': '3.Rahbariyat'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': '1.Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name_plural': '2.Yangiliklar'},
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('ESKI', 'Eski')], default='YANGI', max_length=50),
        ),
    ]
