# Generated by Django 5.1 on 2024-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_options_alter_management_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
