# Generated by Django 5.1 on 2024-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_status_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('XODIM', 'Xodim'), ('TALABA', 'Talaba'), ('PROFESSOR', 'Professor')], max_length=100, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('ESKI', 'Eski')], default='YANGI', max_length=50),
        ),
    ]
